version: "3.3"
x-development-volumes: &development-volumes
  volumes:
    - ./docs:/workspace/app/docs/
    - ./tests:/workspace/app/tests/
    - ./src:/workspace/app/src/
    - ./Makefile:/workspace/app/Makefile
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./pdm.lock:/workspace/app/pdm.lock
    - ./mkdocs.yml:/workspace/app/mkdocs.yml
    - ./tsconfig.json:/workspace/app/tsconfig.json
    - ./package.json:/workspace/app/package.json
    - ./vite.config.ts:/workspace/app/vite.config.ts
services:
  localmail:
    image: mailhog/mailhog:v1.0.0
    container_name: localmail
    ports:
      - "8025:8025"
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    image: app:latest-dev
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  worker:
    image: app:latest-dev
    command: litestar workers run
    restart: always
    <<: *development-volumes
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env.example
  migrator:
    image: app:latest-dev
    command: litestar database upgrade --no-prompt
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
