# https://nixpacks.com/docs/configuration/file

providers = ['python'] # force python as the only provider, otherwise railway may think this is a node project

# set up some variables to minimize annoyance
[variables]
    PIP_DISABLE_PIP_VERSION_CHECK = '1' # the pip update notification is relatively useless in a production environment
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the node update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is is also pretty useless in a production environment
    NIXPACKS_PDM_VERSION = '2.10.3' # set pdm version to install
    NIXPACKS_PYTHON_VERSION = '3.11' # set python version to install
    LITESTAR_SKIP_BUILD_ASSETS = '1' # skip the post_install and pre_build script, the same functionality is achieved below

[phases.setup]
    nixPkgs = ['...', 'nodejs'] # add nodejs since it is needed to build the frontend

[phases.install]
    cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install pdm==$NIXPACKS_PDM_VERSION && pdm install --prod'] # custom install command allows for setting pdm version above

[phases.ci]
    dependsOn = ['setup'] # must run after the setup phase since node is installed in the setup phase
    cmds = ['npm ci'] # install frontend dependencies with clean-install

[phases.build]
    dependsOn = ['ci'] # must run after the ci phase so that node dependencies are available
    cmds = ['npm run build'] # build the frontend
